Fixed routes reloading
Viewstate lib completely reloads all app routes. If engines are used
it's possible that routes are loaded in wrong order and then any
engine route extension defined in main app is overwritten.

How to reproduce:
Conductor adds additional 'edit_xml' action to base_images resource.
If you access e.g. /pools/index page (which calls the viewstate method
which reloads routes) and then if you access tim/base_images/new page,
you should get error:
Undefined method `edit_xml_base_images_path'